minecraft_version=26.1
minecraft_version_range=[26.1,26.1.1)
compile_minecraft_version=26.1
minecraft_dependency=26.1
java_version=25
loaders=fabric,neoforge

fabric_loader_version=0.19.3
fabric_api_version=0.143.14+26.1

neoforge_version=26.1.0.19-beta
