minecraft_version=1.21.8
minecraft_version_range=[1.21.8,1.21.9)

fabric_loader_version=0.18.5
fabric_api_version=0.136.1+1.21.8

neoforge_version=21.8.48

paper_api_version=1.21.8
paper_dev_bundle_version=1.21.8-R0.1-SNAPSHOT
